#!/bin/bash
set -e

NUM_TRANSCRIPTS=$1
TESTS=$2
shift
shift

echo "Arg3: $3"

if [ -n "$3" ]; then
  echo "IMAGE_URI set"
  IMAGE_URI=$3
  shift
fi

if [ -f "$TESTS" ]; then
  TESTS=$(cat $TESTS | tr '\n' ' ')
fi

echo docker run --rm -t $IMAGE_URI /bin/sh -c "\
  set -e; \
  cd /usr/src/barretenberg/cpp/srs_db; \
  ./download_ignition.sh $NUM_TRANSCRIPTS; \
  ./download_ignition_lagrange.sh 12; \
  cd /usr/src/barretenberg/cpp/build; \
  for BIN in $TESTS; do ./bin/\$BIN $@; done"

docker run --rm -t $IMAGE_URI /bin/sh -c "\
  set -e; \
  cd /usr/src/barretenberg/cpp/srs_db; \
  ./download_ignition.sh $NUM_TRANSCRIPTS; \
  ./download_ignition_lagrange.sh 12; \
  cd /usr/src/barretenberg/cpp/build; \
  for BIN in $TESTS; do ./bin/\$BIN $@; done"
