name: Build docker images & run tests

on:
  push:
    branches:
      # run for all pushes to master
      - master
    tags:
      # run for all pushes to any tags
      - "*"
  pull_request:
    # run for all opens/pushes/merges of PRs
    # to run on merge, we use `closed` in conjunction with
    # `if: github.event.pull_request.merged` in job
    types: [opened, reopened, synchronize, closed ]

jobs:
  #checkout:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v3

  wasm-linux-clang:
    runs-on: ubuntu-latest
    #needs: checkout
    #container: aztecprotocol/alpine-build-image
    steps:
      #- name: Install git
      #  - run: |
      #    apk update && apk add git
      #    # UHU?!? The checkout action does exactly the same and that doesn't work.
      #    /usr/bin/git config --global --add safe.directory /__w/barretenberg/barretenberg
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # WARNING: what is this and why is it necessary?
          set-safe-directory: true
          token: ${{ secrets.GITHUB_TOKEN }}
      #- name: Setup environment
      #  run: cd .circleci && source ./setup_env && cd ../
      - name: Build
        run: cd .circleci && source ./setup_env && cd ../ && pwd && bash .circleci/cond_spot_run_build barretenberg-wasm-linux-clang 64
